# Generated by Django 3.1.4 on 2021-11-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblassets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assettype', models.SmallIntegerField(blank=True, db_column='assetType', null=True)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=255, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblassets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblbadges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgeid', models.IntegerField(blank=True, db_column='badgeID', null=True)),
                ('lastbatterychange', models.DateTimeField(blank=True, db_column='lastBatteryChange', null=True)),
            ],
            options={
                'db_table': 'tblbadges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbllocationdata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nodeid', models.IntegerField(blank=True, db_column='nodeID', null=True)),
                ('badgeid', models.IntegerField(blank=True, db_column='badgeID', null=True)),
                ('stampedtime', models.DateTimeField(blank=True, db_column='stampedTime', null=True)),
            ],
            options={
                'db_table': 'tbllocationdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblnodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.IntegerField(blank=True, db_column='nodeID', null=True, unique=True)),
                ('firingsequence', models.IntegerField(blank=True, db_column='firingSequence', null=True)),
            ],
            options={
                'db_table': 'tblnodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblrooms',
                'managed': False,
            },
        ),
    ]
